/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import game.echoes.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasMainClass() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
